services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    hostname: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./volumes/synapse:/data
      - ./synapse/homeserver.yaml:/data/homeserver.yaml
      - ./synapse/templates:/data/templates
    ports:
      - "8008:8008"     # HTTP port - direct access
      - "8448:8448"     # Federation port
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - synapse_network
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8008/health || exit 1"]
      start_period: "30s"
      interval: "30s"
      timeout: "10s"
      retries: 3

networks:
  synapse_network:
    driver: bridge
